### ISSUE TITLE
Feature request: fresh core install

### ISSUE THREAD

**Issue by davewongillies** [mattpannella/pupdate#224]
pupdate does the right thing and never deletes files, but in some situations some cores do things like rename some of the files like under `Presets` or `Settings` which can cause issues. It'd be great if `pupdate` had the ability to optionally do a fresh core install where it purges everything in `Assets/<core>/<core json directory>`,  `Cores/<core>`, `Presets/<core>` & `Settings/<core>`.

**Comment by mattpannella** [comment]
lemme know if this does what you need

**Comment by davewongillies** [comment]
> lemme know if this does what you need

👍🏻 Perfect!
