### ISSUE TITLE
Error downloading pupdate_win.zip

### ISSUE THREAD

**Issue by ninetynein** [mattpannella/pupdate#240]
**Describe the bug**
Unable to download pupdate_win.zip from https://github.com/mattpannella/pupdate/releases/tag/3.2.1  All other builds download.

**To Reproduce**
1. Go to https://github.com/mattpannella/pupdate/releases/tag/3.2.1
2. Click on 'pupdate_win.zip'

**Secure Connection Failed

An error occurred during a connection to objects.githubusercontent.com.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

Thanks!

**Comment by mattpannella** [comment]
the link works for me. not sure why your browser is having issues with githubs ssl cert
