### ISSUE TITLE
Feature request: Include "Memories" folder in backup along with "Saves"

### ISSUE THREAD

**Issue by clara2g** [mattpannella/pupdate#243]
Memories are a very important feature of the Analogue Pocket for those who play with cartridges. They are like save games/states for the original cartridge games and I think a lot of people myself included would like to have them backed up along the regular saves with your amazing updater by just adding the "Memories" folder from the root of the SD to the backup.

Thank you. Kind regards :)

**Comment by mattpannella** [comment]
good idea, i'll probably work on this soon-ish

**Comment by mattpannella** [comment]
should be in the next release
