### ISSUE TITLE
PUPDATE DOESNT READ JTBUBL CORE

### ISSUE THREAD

**Issue by valdeaceras** [mattpannella/pupdate#254]
**Describe the bug**
Hi! I don't know why but when I run pupdate , the program skip the core jtbubl. Until now, pupdate update it without problems.

**To Reproduce**
Run pupdate and see cores. jtbubl is not there.

**Expected behavior**
jtbubl must be appear in the cores read.

**Screenshots**
![problem_jtbubl](https://github.com/mattpannella/pupdate/assets/38540566/b5092224-f7cc-4d17-b5ae-252d4906da86)

**Desktop (please complete the following information):**
Windows 10

**Contents of settings file**
please attach the contents of pupdate_settings.json

**Comment by mattpannella** [comment]
do you have the jtbeta file present on your sd card? it will skip beta cores without that there

**Comment by valdeaceras** [comment]
Hi,
Thanks for the response. You are right, the beta file was not the correct. But this function is recent. No much time ago, when I run the pupdate all and the beta file was not the correct, I had a message that said something like "The beta is not valid", but the core was downloaded. 

Regards,

**Comment by hallem** [comment]
So if you don't have a beta key installed with the core you won't be able to run any of the ROMs for the core. So what's the point of having a core you can't use downloaded automatically by pupdate?

Also, this will be the behavior for all the Jotego beta cores. There is a fix pending that will add the message to the summary at the end of the update to let you know the core was skipped because the beta key was missing.

**Comment by valdeaceras** [comment]
Hi,

You are right. It has no sense download the core if you can't play. But not much time ago, when I make a mistake with a jtbeta file, I realise with a message when the core was downloaded. Now I know that cores with bad jtbeta file are skipped and it has totally sense. 
The fix pending you coment will be appreciated.

Thanks,
Regards,

**Comment by mattpannella** [comment]
it shouldn't skip a core if you have an invalid beta key because at that point it only checks if there is a key at all, not if its correct. the check if its valid happens after the core is updated
are you sure you didnt just delete or rename jtbeta.zip on yoru sd card?

**Comment by hallem** [comment]
@valdeaceras were you able to get this resolved with a good beta key file?
