### ISSUE TITLE
`pupdate update` prompting when complete with `Press any key to continue.`

### ISSUE THREAD

**Issue by datajerk** [mattpannella/pupdate#268]
**Describe the bug**
`pupdate update` prompting when complete with `Press any key to continue.`

This is not ideal for scripting.

**To Reproduce**
1. `pupdate update`
2. get annoyed with `Press any key to continue.`  "continue" with what exactly?  exiting?

**Expected behavior**
Program exits with an RC, no need to prompt to "continue" when there's nothing to "continue".

**Screenshots**
It's a CLI tool, screenshots are not necessary.  Text:
```
Update Process Complete.

Please consider supporting jotego for their work on the jtsimson (jotego.jtsimson) core:
https://github.com/sponsors/jotego
https://www.patreon.com/jotego
https://www.paypal.me/topapate

Fun fact! The ONLY cores that support save states and sleep are the following:
    agg23.NES, agg23.Tamagotchi_P1, agg23.WonderSwan, Spacemen3.PDP1,
    Spiritualized.GB, Spiritualized.GBA, Spiritualized.GBC, Spiritualized.GG,
    Spiritualized.SG-1000, Spiritualized.SMS
Please don't bother the developers of the other cores about this feature. It's a lot
of work and most likely will not be coming.
Press any key to continue.
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 14.3.1

**Contents of settings file**
No--has github token.

**Comment by mattpannella** [comment]
woops, small regression I didn't catch in the code refactor. it should only prompt to continue if you don't pass any cli parameters
