### ISSUE TITLE
Download Pocket Library Images needs an install progress bar

### ISSUE THREAD

**Issue by ajorg** [mattpannella/pupdate#273]
**Describe the bug**

Because it can take a very long time, the "Download Pocket Library Images" feature downloads needs an install progress bar. I tried to use it several times and each time I thought it had stalled. Finally I tried manually installing the library images and realized it was probably doing just fine, but was taking a long time.

**To Reproduce**

Go to "Pocket Setup" then "Download Pocket Library Images".  
After it reaches "Installing..." it appears to stall.

**Expected behavior**

Because this is made up of hundreds of small files, it takes a very long time to extract and install. If the files were first counted, pupdate could make up a progress bar of the files involved.

**Screenshots**

```
               _                              
 __        _  | |                             
|  |   ___| |_|_|___    _____ ___ ___ ___ _ _ 
|  |__| -_|  _| |_ -|  |     | . |_ -| -_| | |
|_____|___|_|   |___|  |_|_|_|___|___|___|_  |
                                         |___|
                                              
Please consider supporting agg23 for their work on the Tamagotchi (agg23.Tamagotchi_P1) core:
https://github.com/sponsors/agg23

Remaining GitHub API calls: 48

Choose your destiny:
  [0] Download Platform Image Packs
=>[1] Download Pocket Library Images
  [2] Download GameBoy Palettes
  [3] Generate Instance JSON Files (PC Engine CD)
  [4] Generate Game & Watch ROMs
  [5] Enable All Display Modes
  [6] Apply 8:7 Aspect Ratio to Super GameBoy cores
  [7] Restore 4:3 Aspect Ratio to Super GameBoy cores
  [8] Go Back

Loading Assets Index for 'openFPGA-Files'...
Downloading 'Library_Image_Set_v1.0.zip'
Finished downloading 'Library_Image_Set_v1.0.zip'                                                                                                                           
Installing...
```

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: 12

**Contents of settings file**
please attach the contents of pupdate_settings.json
[pupdate_settings.json](https://github.com/mattpannella/pupdate/files/14532763/pupdate_settings.json)

**Comment by mattpannella** [comment]
working on it

**Comment by mattpannella** [comment]
3.9.0 should have what you need
