### ISSUE TITLE
Is it possible update/install  only new cores? 

### ISSUE THREAD

**Issue by Mika73** [mattpannella/pupdate#275]
I have question about pocket updater. Is it possible update new cores only? Usually use update all but it update everything. At select core menu there’s option update new/latest cores default. But I still end up to that update all at menu. When start up pocket updater it shows new cores if those are there. But is it possible just add those new cores?😮

**Comment by hallem** [comment]
When starting pupdate and using the menu, depending on your settings, it will ask you if you want to include any new cores in your update all. If you do choose to add those cores, it makes a change to the settings to add those cores to the `update all` process. You would then need to run `update all` to both update any other cores that have updates AND install the new ones.

If you want to just update or install a single core, you can do so on the command line by running `pupdate update -c "<core name>"`.

Currently pupdate is not setup to just update or install some cores without running the entire `update all` process. Is there a reason that running `update all` isn't something you want to do?

**Comment by mattpannella** [comment]
yeah `pupdate update -c` will do what you want

**Comment by Mika73** [comment]
When start pupdate it shows if there’s new cores, like new arcade games etc. You can select these. If you just wanted add these new games to Analogue pocket, I don’t know how. So I usually use update all because it’s easy and does everything. But because it goes true everything and all cores that’s already installed to sd card it takes time. So I was thinking is it possible just add those new games that are shown at start up and not check games/cores that already are at sd card? Lähetetty iPhonestaMichael Hallett ***@***.***> kirjoitti 15.3.2024 kello 23.06:﻿
When starting pupdate and using the menu, depending on your settings, it will ask you if you want to include any new cores in your update all. If you do choose to add those cores, it makes a change to the settings to add those cores to the update all process. You would then need to run update all to both update any other cores that have updates AND install the new ones.
If you want to just update or install a single core, you can do so on the command line by running pupdate update -c "<core name>".
Currently pupdate is not setup to just update or install some cores without running the entire update all process. Is there a reason that running update all isn't something you want to do?

**Comment by hallem** [comment]
Right, you have to run update all to install the new cores and keep the others up to date. If you don't want to run update all, your only other choice is to run the command both @mattpannella and I mentioned for a single core. That command will install or update a single core.

The way pupdate works, it's not possible to just install a small list or update a small list without doing the entire process.
