### ISSUE TITLE
Firmware update failing

### ISSUE THREAD

**Issue by Drako** [mattpannella/pupdate#278]
Version 3.9.0

When I run "Update All" or even just "Update Firmware", the update fails with the following message:

```
Checking for firmware updates...
Firmware update found. Downloading...
Well, something went wrong. Sorry about that.
One or more errors occurred. (A task was canceled.)
Press any key to continue.
```

At the time the most recent downloadable firmware version is 2.2.
Already on the SD card is the "pocket_firmware_2_1.bin" which I'm not sure if I'm supposed to delete first.

Manually I can easily download the current firmware image. And it loads even faster than the updater takes to display the rather useless error.
Sadly I also couldn't find any `--verbose` option to get more information on the error.

**Comment by Drako** [comment]
After manually updating the firmware, updating the rest works fine.
It would still be interesting to find out, what the source of the issue here is.

**Comment by hallem** [comment]
There isn't a verbose option yet. We're looking into what can be done for better logging. The error message you screen capped though suggests something is wrong with the request to get the file. What version of pupdate are you running?

**Comment by hallem** [comment]
I've tested it out on a few different SD cards and local Pocket folders. I wasn't able to reproduce the issue. If you wouldn't mind, try deleting the firmware on your SD card and then running the `update firmware` again to see if it was just an intermittent issue with downloading the file.

**Comment by Drako** [comment]
> What version of pupdate are you running?

As mentioned in the question: 3.9.0

> If you wouldn't mind, try deleting the firmware on your SD card and then running the update firmware again to see if it was just an intermittent issue with downloading the file.

I'll try that and add a comment with the results.
