### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by Shadow322** [mattpannella/pupdate#284]
Updating to v3.9.1 is broken i press I to update it closes and deleted the EXE so its broken again

**Comment by mattpannella** [comment]
manually install it by downloading the release and unzipping the exe to your directory

**Comment by Shadow322** [comment]
> manually install it by downloading the release and unzipping the exe to your directory

yea i know that is it going to be fixed?

**Comment by mattpannella** [comment]
if you want more help than that you're going to need to actually give me some information here, otherwise I'm just closing this
