### ISSUE TITLE
Selecting "[8] Settings" crashes to desktop (windows)

### ISSUE THREAD

**Issue by lunchpacked130** [mattpannella/pupdate#289]
**Describe the bug**
In Version 3.10.0, selecting "[8] Settings" gives the following message:
"Well, something went wrong. Sorry about that. 
Object reference not set to an instance of an object."
Then crashes to desktop.

**To Reproduce**
1. Start Pupdate.exe v3.10.0
2. Click on "[8] Settings"
3. See error

**Expected behavior**
Access to settings doesn't crash to desktop.

**Desktop (please complete the following information):**
 - OS: win 11
 - pupdate 3.10.0

Things tried that didn't work:
Redownloaded pupdate from github directly
Deleted pupdate_settings.json so pupdate would generate a fresh one.

**Comment by mattpannella** [comment]
should be fixed

**Comment by lunchpacked130** [comment]
works with updated 3.10.1 :)
