### ISSUE TITLE
Windows Defender flags pupdate as trojan on Windows 10

### ISSUE THREAD

**Issue by arniegeddon** [mattpannella/pupdate#291]
**Describe the bug**
After updated from 3.9.1 to 3.10.1 and extracting pupdate.exe from zip file, windows defender flags the exe as :
 Trojan:Win32/Wacatac.B!ml

**To Reproduce**
1. Launce pupdate.exe and update to version 3.10.1 
2. Extract pupdate.exe from pupdate.zip

**Screenshots**
![pupdate_virus_message](https://github.com/mattpannella/pupdate/assets/5017206/1df97430-8256-4ec4-8738-7440bc04cb4b)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version 22H2

**Contents of settings file**
{
  "config": {
    "download_assets": true,
    "github_token": "",
    "download_firmware": true,
    "preserve_platforms_folder": false,
    "delete_skipped_cores": true,
    "download_new_cores": "yes",
    "build_instance_jsons": true,
    "crc_check": true,
    "fix_jt_names": true,
    "skip_alternative_assets": true,
    "backup_saves": false,
    "backup_saves_location": "Backups",
    "show_menu_descriptions": true,
    "use_custom_archive": true,
    "archives": [
      {
        "name": "default",
        "type": "internet_archive",
        "archive_name": "openFPGA-Files"
      },
      {
        "name": "custom",
        "type": "custom_archive",
        "archive_name": "custom",
        "url": "https://updater.retrodriven.com",
        "index": "updater.php"
      },
      {
        "enabled": false,
        "name": "agg23.GameAndWatch",
        "type": "core_specific_archive",
        "archive_name": "fpga-gnw-opt",
        "file_extensions": [
          ".gnw"
        ]
      }
    ]
  },
  "core_settings": {
    "agg23.Arduboy": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.Pong": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.NES": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.PC Engine": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.PokemonMini": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.SNES": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.Asteroids": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.Dominos": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.DonkeyKong": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.Genesis": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.LunarLander": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.RadarScope": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.SpaceRace": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.SuperBreakout": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.QBert": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Mazamars312.NeoGeo": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Mazamars312.Amiga": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "nullobject.tecmo": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.bankpanic": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.congo": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.digdug": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.galaga": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.gberet": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.pooyan": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.supervision": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.xevious": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spacemen3.PDP1": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.GB": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.GBA": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.GBC": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.NES": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.GG": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.SMS": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.SG-1000": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.VideoBrain": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Supervision": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.SuperGB": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Studio2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Odyssey2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Intv": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Megaduck": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Genesis": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Gameking": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Gamate": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Creativision": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Coleco": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.ChannelF": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.7800": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Arcadia": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Adventurevision": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.2600": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.bakraid": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.batrider": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.garegga": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.snowbros2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtdd": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtdd2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtgng": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtkicker": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtkunio": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtmikie": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtpinpon": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtroadf": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtroc": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtsbaskt": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jttrack": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtvigil": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtyiear": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtpang": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcontra": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.GameAndWatch": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.Tamagotchi_P1": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.WonderSwan": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "antongale.exerion": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "antongale.performan": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "antongale.slapfight": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "antongale.taitosj": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "atrac17.pipibibs": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "atrac17.truxton2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.kingdmgp": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.sstriker": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jt1942": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtaliens": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtbtiger": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtbubl": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcastle": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcomsc": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcop": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcps1": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcps15": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcps2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtexed": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtfround": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtgunsmk": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtkarnov": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtkiwi": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtninja": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtoutrun": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtrastan": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jts16": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jts16b": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtsarms": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtsectnz": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtsf": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtshanon": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtshouse": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtsimson": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jttmnt": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jttora": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jttrojan": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Mazamars312.NeoGeo_Overdrive": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Mazamars312.PC Engine CD": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "RndMnkIII.alphamission": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "somhi.flappybird": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "AwesomeDolphin.SpaceInvaders": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "budude2.GBC": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "budude2.GB": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtngp": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtvulgus": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.AsteroidsDeluxe": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.DonkeyKong3": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.DonkeyKongJr": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.Druaga": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.MarioBros": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.Vectrex": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jt1943": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "rolandking.Jailbreak": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtmx5k": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.Defender": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.Robotron": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtkchamp": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Mazamars312.NeoGeo_Analogizer": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "RndMnkIII.alphamission_Analogizer": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcommnd": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "markus-zzz.MyC64": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.Gaplus": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.NES_Analogizer": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    }
  }
}

**Comment by hallem** [comment]
Where did you download pupdate from?

**Comment by arniegeddon** [comment]
Github. I get the same behaviour if I download the latest pupdate.zip and extract.

**Comment by mattpannella** [comment]
windows defender is trigger happy. I'm not sure if there's some kind of process to submit my app to them but I'll be honest, I don't want to jump through that hoop when there's literally no reason for them to be flagging it in the first place

**Comment by arniegeddon** [comment]
No worries. I'll close the issue. I might just move over the the Linux version and that will avoid the warning.
