### ISSUE TITLE
Irem M92 games load to black screen

### ISSUE THREAD

**Issue by mikeyvids** [mattpannella/pupdate#294]
**Describe the bug**
Not sure if this is an issue with update games, core, or my pocket. Updated all via pupdate for Irem M92 and whenever I go to load a game from that board the screen is black.

**To Reproduce**
1. Go to OpenFPGA
2. Click on Irem M92
3. Scroll down to load any game
4. See error as black screen

**Expected behavior**
Expected games to load. Even tried reloading direct from core

**Screenshots**

**Desktop (please complete the following information):**
 - OS 14
 - Latest pocket version (up to date)

**Comment by mattpannella** [comment]
if you have issues with individual cores, please submit issues with their developers. https://github.com/opengateware/arcade-irem_m92
