### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ctafield** [mattpannella/pupdate#295]
**Request**: It would be really useful to "never update this core(s)", or "always grab version X of a specific core".

**Why**: A lot of people seem to have issues with newer versions of a certain core on newer Pockets. Namely, the GBA core. We have to use v1.0 of it, which often involves copying it back over after we've done an update.

**Comment by mattpannella** [comment]
yup that would work

**Comment by ctafield** [comment]
Perfect, thank you!
