### ISSUE TITLE
Pupdate reports wrongly that it's not finding c64 assets

### ISSUE THREAD

**Issue by lunchpacked130** [mattpannella/pupdate#296]
**Describe the bug**
Running [0] Update All reports missing unspecified asset for C64, 

it returns the message:
`Assets not found:`
`\Assets\c64\common`

Not missing any specific roms, just that message.

I have the bios/system files downloaded by pupdate, as well as core reccomended rom files and several more.

**To Reproduce**
1. Click on '[0] Update All]
2. See error in end report

**Expected behavior**
Should report what specific roms are missing or should not display only:
`Assets not found:`
`\Assets\c64\common`

**Other tried actions**
• Redownloaded fresh pupdate from github.

•Formatted sd card and redownloaded C64 core

•Tried on other sd card

No change in results

Just to see if it gave a different result, i also removed the entire "common" folder and contents from assets\c64\ to see if it did anything different.
It downloaded the three bios/system files, but it still shows:
`Assets not found:`
`\Assets\c64\common`

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Pupdate 3.10.1

**Comment by mattpannella** [comment]
i think this is because the c64 core has a blank filename in a dataslot in data.json
```json
{
        "name": "PRG Slot #0",
        "id": "100",
        "required": false,
        "deferload": true,
        "parameters": 9,
        "filename": "",
        "extensions": ["prg"]
    },
```

pretty sure filename should just be removed here. 
obviously i can also patch to ignore blanks.

**Comment by lunchpacked130** [comment]
ah, that makes sense.
thanks for looking into it :)
