### ISSUE TITLE
"Download Missing Assets during 'Update All'" also blocks "Download Assets"

### ISSUE THREAD

**Issue by bevans10037** [mattpannella/pupdate#301]
**Describe the bug**
When the "Download Missing Assets (ROMs and BIOS Files) during 'Update All'" setting is turned off, the assets will also not be downloaded when "3 - Download Assets" is selected.

**To Reproduce**
From a blank pupdate_settings.json, go to the settings, turn off "Download Missing Assets...", reboot the program (it will still download assets before rebooting), then select "3 - Download Assets"

**Expected behavior**
Assets should only not be downloaded specifically in "0 - Update All"; "3 - Download Assets" should be ok I reckon, since you're explicitly asking to download the assets

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 3.10.2

**Contents of settings file**
please attach the contents of pupdate_settings.json
[pupdate_settings.json](https://github.com/mattpannella/pupdate/files/15285734/pupdate_settings.json)

**Comment by mattpannella** [comment]
woops, i wonder when i broke this

**Comment by mattpannella** [comment]
this should be fixed in the latest release
