### ISSUE TITLE
Jotego Neo Geo Pocket doesn't get automatically renamed during "Update All"

### ISSUE THREAD

**Issue by tbalcom** [mattpannella/pupdate#303]
**Describe the bug**
I have the setting to rename Jotego cores during "Update All". It consistently automatically renames all of the Jotego cores except Neo Geo Pocket. The Platforms\*.json files all have the same timestamp except the jtngp.json file after running "Update All". I manually edit the JSON file after running "Update All" and it work's as expected.

**To Reproduce**
1. Run Update All with Rename Jotego Cores setting enabled.
2. All Jotego cores are successfully renamed except the Neo Geo Pocket.

**Expected behavior**
The Jotego core jtngp.json should be successfully renamed from "jtngp" to "Neo Geo Pocket", year to 1998, and owner to "SNK".

**Desktop:**
 - OS: Windows
 - Version 10 22H2 19045.4412

**Contents of settings file**
[pupdate_settings.json](https://github.com/mattpannella/pupdate/files/15369981/pupdate_settings.json)

**Comment by tbalcom** [comment]
I know this particular core was previously [renamed](https://github.com/jotego/jtcores/issues/482). Is pupdate caching the old JSON somewhere?

**Comment by mattpannella** [comment]
the renamed cores use this as the source https://github.com/dyreschlock/pocket-platform-images
since up til now jotego was only releasing arcade cores, it's only checking in the arcade directory for the renamed platforms
should be an easy fix once i have some time

**Comment by mattpannella** [comment]
this should be fixed in the latest release
