### ISSUE TITLE
[Feature Request] Integer Sizing/Scaling options for Super Game Boy Core 8:7 Mode

### ISSUE THREAD

**Issue by Rot-gut** [mattpannella/pupdate#304]
Firstly, the 8:7 mode in the updater for the SGB core is brilliant! I was wondering if there would be a way to enable more scaling options for it so that the Game Boy image can take up the entirety of the Analogue Pocket screen (so while the SGB borders wouldn't be visible, the image of the Game Boy game could at least fit the screen completely). Not sure if the updater would be capable of this or if it's more on the core creator.

**Comment by mattpannella** [comment]
sorry, bearer of bad news, that stuff is all defined in the pocket os, so there's nothing i can do to add more options
the only thing i can do on my end is just add all the available modes to a core, as options

**Comment by Rot-gut** [comment]
> sorry, bearer of bad news, that stuff is all defined in the pocket os, so there's nothing i can do to add more options the only thing i can do on my end is just add all the available modes to a core, as options

That's OK! Thanks for getting back to me. This feature was requested on the Core creator's Github but it seems they abandoned support as it hasn't been updated in a few years.
