### ISSUE TITLE
VIRUS in pupdate 3.10.3

### ISSUE THREAD

**Issue by misterjbam** [mattpannella/pupdate#309]
Gen.Suspicious.Cloud.2 virus is present in the windows version

**Comment by hacknug** [comment]
I don't see any issues in VirusTotal if I scan the windows zip: https://www.virustotal.com/gui/url/9cec4e9f007ed617170e61c84d45b5e02a00e0e939539e2850a7edd8ab1b1dca?nocache=1

**Comment by gregoryjgarcia0** [comment]
Windows Defender finds a trojan in it.

**Comment by fluiddruid** [comment]
I see the same - Win11 V23H2 is blocking 3.10.3. 3.10.2 still works.

**Comment by hacknug** [comment]
Does the same alert show up when you clone the repo? Did you try building it locally?

**Comment by mattpannella** [comment]
windows defender is a pain in my ass

**Comment by Icefyre0** [comment]
Defender has picked up Trojan:Win32/Wacatac.B!ml for me, that was using the pupdate utility itself to update.

**Comment by PsychoFox11** [comment]
Yeah it's removing it whether I update from command line or just downlaod the zip.

**Comment by mattpannella** [comment]
I submitted the application to ms for review. I don't know how defender works but I assume you can just whitelist it

**Comment by BrainGremlins** [comment]
The !ml at the end of the string there is indicative that the result isn't based on comparison to a database, but based on machine learning algorithms. It has a tendency to classify any compressed file to be a virus.... Because viruses tend to come in compressed forms. Yes, it's a bad idea.

**Comment by mattpannella** [comment]
just to update this, Microsoft ghosted me and never did anything with my submission for the whitelist

**Comment by mattpannella** [comment]
I'm just gonna use this down for now
