### ISSUE TITLE
Missing Moonwalker Assets

### ISSUE THREAD

**Issue by nickxcom** [mattpannella/pupdate#313]
**Describe the bug**
Update all does not pull down moonwalker assets. It identifies the missing files, specifically mwalk.rom, mwalkj.rom and mwalku.rom, but does not download them

![missing assets](https://github.com/user-attachments/assets/a37669af-476d-40a7-b8a6-0a23684dff62)

**To Reproduce**
Run update all. 

**Expected behavior**
Missing roms would be downloaded

**Contents of settings file**
[pupdate_settings.json](https://github.com/user-attachments/files/16198043/pupdate_settings.json)

**Comment by nickxcom** [comment]
Did a little more digging. The screenshot above is after running the update all command. If I actually CHECK the crawl of what assets are actually checked in the JTS 18 core, the update processes doesn't actually check for those assets. See attached 
![jts18](https://github.com/user-attachments/assets/15f2a6f2-0bc7-4353-9a33-e68ed7bf71fc)

**Comment by Jayhawkers** [comment]
The Moonwalker roms aren't in the archive:

https://archive.org/download/openFPGA-Files

**Comment by nickxcom** [comment]
> The Moonwalker roms aren't in the archive:
> 
> https://archive.org/download/openFPGA-Files

Thank you!! Someone offsite filled me in too, I could have sworn MiSTer update all and pupdate pulled from the same source for arcade roms. I was completely wrong! I will be patient and wait for it to hit the archive

**Comment by mattpannella** [comment]
they've been uploaded

**Comment by nickxcom** [comment]
Thanks for the heads-up! Sorry to bother you :)
