### ISSUE TITLE
Feature request: Setup for Analogizer in Jotego Cores

### ISSUE THREAD

**Issue by rp-jt** [mattpannella/pupdate#314]
Hello!

In Jotego, we have just added compatibility with the [Pocket Analogizer](https://github.com/RndMnkIII/Analogizer) device, however, for setting up video and controller options we have decided to use a _configuration file_ containing a 32-bit number.

To create this file, we have created a [setup tool](https://github.com/jotego/jtcores/raw/master/modules/jtframe/bin/jt-crtcfg.py) in the form of a python script. As it is explained [here](https://github.com/jotego/jtbin/wiki/Analogue-Pocket-Cores#using-analogizer-with-jt-cores), the generated file (`crtcfg.bin`) has to be added manually to the SD card in the path `Assets/jtpatreon/common` for it to be read by the cores.

We thought it could be interesting for this feature to be added to the Updater if possible.

This _configuration file_ can be divided in three different sections: Analog Video (12 bits), Snac Controllers (8 bits) and the rest (12 bits, now unused).

In the **Analog Video** section, the values corresponding to the different options is:
Value | Option
-------|--------------------------------------------|
   0x820   | RBGS       (SCART)                         |
   0xC08   | RGsB                                       |
   0xA08   | YPbPr      (Component video)               |
   0x900   | Y/C NTSC   (SVideo, Composite video)       |
   0x980   | Y/C PAL    (SVideo, Composite video)       |
   0x801   | Scandoubler RGBHV (SCANLINES  0%)          |
   0x803   | Scandoubler RGBHV (SCANLINES 25%)          |
   0x805   | Scandoubler RGBHV (SCANLINES 50%)          |
   0x807   | Scandoubler RGBHV (SCANLINES 75%)          |
   0x000   | Disable Analog Video                       |

As for the **SNAC Controllers**:
Value | Option
-------|--------------------------------------------|
   0x00   | None                                       |
   0x01   | DB15 Normal                                |
   0x02   | NES                                        |
   0x03   | SNES                                       |
   0x04   | PCE 2BTN/6BTN                              |
   0x06   | PCE Multitap                               |

This way, the final file named `crtcfg.bin`  should have a binary number in the form: Video-SNAC-000000000000, placed in `Assets/jtpatreon/common` .

Let me know what you think and if there might be any doubt about it.
Thanks!

**Comment by mattpannella** [comment]
i think to make it easier on my end, i will port the python to native c# code and just integrate it directly into pupdate. I just tinkered a bit with executing python from within c# and it's a huge pain in the ass lol

**Comment by mattpannella** [comment]
if the values in the maps ever change or additional ones are added, i can always just update to match

**Comment by rp-jt** [comment]
Thanks @mattpannella , that sounds like a good option

**Comment by mattpannella** [comment]
release with 3.11.0

**Comment by rp-jt** [comment]
Hello again @mattpannella !
We did a small change and now for the option SNAC Controller: PCE 2BTN/6BTN, the value is 0x05 instead of 0x04
Would you mind adjusting it? Thanks!

**Comment by mattpannella** [comment]
pushing a build with the tweak in a bit

**Comment by mattpannella** [comment]
updated in v3.12.0
