### ISSUE TITLE
getting error message

### ISSUE THREAD

**Issue by acidrain97** [mattpannella/pupdate#319]
Current version
3.11.1
Windows version.

after running Update all  getting the following error message:

Well, something went wrong. Sorry about that.
Object reference not set to an instance of an object.
Press any key to continue.

program exits

Went and deleted pupdate_settings.json, reran same thing.

Last couple of updates this started to happen. Any clue what could be causing this?

thx

**Comment by clumbo** [comment]
Also seeing the same message

**Comment by hallem** [comment]
Can you provide a copy of the output from pupdate so we can get more information on when and where it's failing please? @clumbo @acidrain97

**Comment by mattpannella** [comment]
been pretty busy lately so i havent had much time to dedicate to this. are you downloading every core, or just a select few?

**Comment by hallem** [comment]
hey just checking in, are you seeing this problem or has it gone away?

**Comment by mattpannella** [comment]
I'll reopen if this comes up again
