### ISSUE TITLE
Analog display mode limit?

### ISSUE THREAD

**Issue by andrewkendall** [mattpannella/pupdate#328]
I’m sure people have noticed this already, but just in case: I think the Analog firmware 2.3 has a limit on how many display modes can be used on a core. I was really excited for the Lynx screen filters, so I enabled all of them as soon as I updated the firmware. By default, I can’t use all the screen modes. It stops working at the Original Lynx mode.

However, if I manually edit the config file and remove some modes, I can use the Lynx ones without any problems. I don’t think this is a major issue — I’d be fine losing the Game Boy screen modes from most cores.

Steps to replicate: enable all display modes, then try the Lynx core, cycling through all modes with the D-pad combo.

**Comment by mattpannella** [comment]
yeah everyone kinda stumbled into this at the same time
i think the real fix is letting you choose which modes to enable

**Comment by mattpannella** [comment]
i havent reviewed yet, but #331 should cover this
