### ISSUE TITLE
Enabling GB Display Modes on GB cores

### ISSUE THREAD

**Issue by dyreschlock** [mattpannella/pupdate#333]
With the new update, there are generic display modes enabled on cores, and then specific display modes enabled on cores they were specifically designed for.

The GameBoy has its 3 display modes, but these modes require cores to output video in a specific way. Only budude's GB core (also GBC and Boogerman's Irem M92 core) support these modes in openFPGA at the moment. 

The spiritualized GB core does not support these display modes, as far as I'm aware, so should pupdate being enabling them on that core?

(sorry if this was already discussed and decided upon)

**Comment by mattpannella** [comment]
hm yeah, right now it just maps the display modes to the matching cores, based on their platform. I guess we could add a special case to exclude the spiritualized one

**Comment by hallem** [comment]
Yeah that's a tough one. There's an ability coming soon to allow you to control what display modes go where as well as a curated list, but it keys off of platform Id so not exactly straight forward to exclude the spiritualized cores.

**Comment by hallem** [comment]
I figured out how to do this. I added a exclude cores option to the display modes json file. It's included in #349
