### ISSUE TITLE
Uninstalling core doesn't clean up assets folder entry

### ISSUE THREAD

**Issue by StevenJDH** [mattpannella/pupdate#337]
**Describe the bug**
I noticed that when uninstalling a core, you are asked if you would like to remove the associated folder under assets. However, if you say yes, the folder is still left behind, which requires manual cleanup. There are no errors, and the output indicates it was removed, but it wasn't. I'm using version 3.15 of the app.

**To Reproduce**
1. Uninstall a core.
2. When prompted to remove associated assets folder, say yes.
3. Check the assets folder listed in the output as removed to find it still there.

**Expected behavior**
Associated asset folder is removed if yes is selected.

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by mattpannella** [comment]
this is on purpose so we don't delete your rom files. the updater never touches Assets/{platform}/common
that option is for core specific assets only. Assets/{platform}/{corename}

**Comment by mattpannella** [comment]
just to add another reason 
if you have 2 GB cores, uninstalling one of them would delete everything because Assets/fb/common is shared by any core supporting the platform
