### ISSUE TITLE
Some suggestions for the display modes

### ISSUE THREAD

**Issue by Trevbot911** [mattpannella/pupdate#343]
I don't know if this is the best place to put this but I have a couple of changes that might be good for the Enable Recommended Display Modes option.
First off, add the GBC filters to GB and SGB (and maybe also the GBA filters to all of those), and the PC Engine filters to the PC Engine CD.
And second, make the console-specific filters be defined first in the video.json file.  That way, if you like to use the button combinations to switch filters, you'll see the ones recommended for the console before the generic ones.

**Comment by hallem** [comment]
The recommended display modes was just a baseline suggestion if you didn't really want to think about it that a few of us discussed in the discord. There is a way to download that JSON file from GitHub and then set use local display modes to true in the settings. That will allow you to define your own.

Additionally, you can also got the pocket setup --> add display modes menu to setup things manually for all or just selected cores.

For the console specific filters, this has already been fixed and will be released once we cut a new version.
