### ISSUE TITLE
"Missing or incorrect License file" for Jotego and Pram0d cores.

### ISSUE THREAD

**Issue by samson7point1** [mattpannella/pupdate#344]
**Describe the bug**
The root directory where the updater is running contains the latest jtbeta.zip, the "Coin-Op Collection" has been enabled in the settings, and I have provided the required information to enable downloading a Coin-Op Collection license.

When running the updater without arguments and selection option 0 "Update All" the following is output is observed:

> JT beta key detected. Extracting...
> Retrieving Coin-Op Collection license...
> License successfully downloaded.

However at the conclusion of the Update All process, the following message is output:

> Update Process Complete.
> Missing or incorrect License file for the following cores:
> jotego.jtmidres
> jotego.jtngpc
> jotego.jtriders
> jotego.jtrumble
> jotego.jts18
> jotego.jtwwfss
> pram0d.narc
> pram0d.smashtv

**To Reproduce**
1. Place the most recent jtbeta.zip file from Patreon in the root of the update directory
2. Run the updater without arguments
3. Enable "Coin-Op Collection" in the updater options
4. Follow instructions to download the "Coin-Op Collection" License
5. Observe the error

**Expected behavior**
Jotego and Pram0d beta cores successfully licensed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 39

**Contents of settings file**
please attach the contents of pupdate_settings.json
{
  "config": {
    "download_assets": true,
    "github_token": "",
    "download_firmware": true,
    "preserve_platforms_folder": false,
    "delete_skipped_cores": false,
    "download_new_cores": "ask",
    "build_instance_jsons": true,
    "crc_check": true,
    "fix_jt_names": true,
    "skip_alternative_assets": true,
    "backup_saves": false,
    "backup_saves_location": "Backups",
    "show_menu_descriptions": true,
    "use_custom_archive": false,
    "auto_install_updates": false,
    "coin_op_beta": true,
    "temp_directory": null,
    "patreon_email_address": "<redacted, confirmed correct in file>",
    "use_local_pocket_extras": false,
    "use_local_display_modes": false,
    "archives": [
      {
        "name": "default",
        "type": "internet_archive",
        "archive_name": "openFPGA-Files"
      },
      {
        "name": "custom",
        "type": "custom_archive",
        "archive_name": "custom",
        "url": "https://updater.retrodriven.com",
        "index": "updater.php"
      },
      {
        "enabled": false,
        "name": "agg23.GameAndWatch",
        "type": "core_specific_archive",
        "archive_name": "fpga-gnw-opt",
        "file_extensions": [
          ".gnw"
        ]
      }
    ]
  },
  "core_settings": {
    "agg23.Arduboy": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.GameAndWatch": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.NES": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.NES_Analogizer": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.PC Engine": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.PC Engine_Analogizer": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.PokemonMini": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.Pong": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.SNES": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.SNES_Analogizer": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.Tamagotchi_P1": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "agg23.WonderSwan": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "antongale.exerion": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "antongale.performan": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "antongale.slapfight": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "antongale.taitosj": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "atrac17.pipibibs": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "atrac17.tekipaki": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "atrac17.truxton2": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "AwesomeDolphin.SpaceInvaders": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.bankpanic": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.congo": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.digdug": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.galaga": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.gberet": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.pooyan": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.supervision": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "boogermann.xevious": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "budude2.GB": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "budude2.GBC": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "budude2.Lynx": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.Asteroids": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.Dominos": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.DonkeyKong": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.Genesis": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.Genesis_Analogizer": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.LunarLander": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.QBert": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.RadarScope": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.SpaceRace": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "ericlewis.SuperBreakout": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jt1942": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jt1943": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtaliens": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtbiocom": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtbtiger": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },works well we will ma
    "jotego.jtbubl": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcastle": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcircus": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcommnd": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcomsc": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcontra": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcop": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcps1": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcps15": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtcps2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtdd": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtdd2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtexed": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtflane": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtfround": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtgng": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtgunsmk": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtkarnov": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtkchamp": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtkicker": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtkiwi": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtkunio": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtlabrun": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtmidres": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true,
      "requires_license": true
    },
    "jotego.jtmikie": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtmx5k": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtngp": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtngpc": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true,
      "requires_license": true
    },
    "jotego.jtninja": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtoutrun": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtpang": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtparoda": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtpinpon": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtrastan": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtriders": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true,
      "requires_license": true
    },
    "jotego.jtroadf": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtroc": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtrumble": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true,
      "requires_license": true
    },
    "jotego.jts16": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jts16b": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jts18": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true,
      "requires_license": true
    },
    "jotego.jtsarms": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtsbaskt": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtsectnz": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtsf": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtshanon": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtshouse": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtsimson": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtslyspy": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jttmnt": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jttoki": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jttora": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jttrack": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jttrojan": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtvigil": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "jotego.jtwwfss": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true,
      "requires_license": true
    },
    "jotego.jtyiear": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "markus-zzz.MyC64": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Mazamars312.Amiga": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Mazamars312.NeoGeo": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Mazamars312.NeoGeo_Analogizer": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Mazamars312.PC Engine CD": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Mazamars312.PC Engine CD_Analogizer": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "nullobject.tecmo": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.AsteroidsDeluxe": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.Defender": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.DonkeyKong3": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.DonkeyKongJr": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.Druaga": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.Gaplus": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.Gauntlet": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.Gauntlet_Analogizer": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.Joust2": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.MarioBros": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.Robotron": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.System1": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.System1_Analogizer": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "obsidian.Vectrex": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "opengateware.irem_m92": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "opengateware.irem_m92_Analogizer": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.bakraid": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.batrider": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.doubledragoniii": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.garegga": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.kingdmgp": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.narc": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true,
      "requires_license": true
    },
    "pram0d.smashtv": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true,
      "requires_license": true
    },
    "pram0d.snowbros2": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.sstriker": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "pram0d.wrestlefest": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "RndMnkIII.alphamission": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "RndMnkIII.alphamission_Analogizer": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "rolandking.Athena": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "rolandking.Jailbreak": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "somhi.flappybird": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Spacemen3.PDP1": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.2600": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.7800": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Adventurevision": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Arcadia": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.ChannelF": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Coleco": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Creativision": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Gamate": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Gameking": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.GB": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.GBA": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.GBC": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Genesis": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.GG": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Intv": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Megaduck": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.NES": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Odyssey2": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.SG-1000": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.SMS": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Studio2": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.SuperGB": {
      "skip": false,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.Supervision": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "Spiritualized.VideoBrain": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    },
    "tsalvo.varvara": {
      "skip": true,
      "download_assets": true,
      "platform_rename": true
    }
  }

**Comment by mattpannella** [comment]
are the license files in the correct locations?
Assets/jtpatreon/common and Assets/coinop/common?

**Comment by samson7point1** [comment]
FWIW, if I manually create Assets/jtpatreon/common and Assets/coinop/common and place the corresponding license files in them, the behavior of the updater is unchanged, it still reports that all of the beta cores are unlicensed.

**Comment by mattpannella** [comment]
huh, that's odd...those directories should be created if they're missing. but weirder is you manually created them and it still failed. possibly a permissions issue on the 2nd issue?

**Comment by samson7point1** [comment]
The updater built the entire file structure from scratch yesterday, and created those license files itself from the jtbeta.zip and whatever it downloaded from Patreon. 

I used the same user account to manually create the directories as I did to run the updater. The directories are all set to 755, and the files are 644.

> [user@fedora pupdate_linux]$ ls -ald Assets/coinop
> drwxr-xr-x. 3 user user 20 Sep 24 09:18 Assets/coinop
> [user@fedora pupdate_linux]$ ls -ald Assets/coinop/common
> drwxr-xr-x. 2 user user 24 Sep 24 09:18 Assets/coinop/common
> [user@fedora pupdate_linux]$ ls -ald Assets/coinop/common/coinop.key
> -rw-r--r--. 1 user user 16 Sep 24 09:18 Assets/coinop/common/coinop.key
> [user@fedora pupdate_linux]$ ls -ald Assets/jtpatreon
> drwxr-xr-x. 3 user user 20 Sep 24 09:18 Assets/jtpatreon
> [user@fedora pupdate_linux]$ ls -ald Assets/jtpatreon/common
> drwxr-xr-x. 2 user user 22 Sep 24 09:18 Assets/jtpatreon/common
> [user@fedora pupdate_linux]$ ls -ald Assets/jtpatreon/common/beta.bin
> -rw-r--r--. 1 user user 4 Sep 24 09:18 Assets/jtpatreon/common/beta.bin

**Comment by samson7point1** [comment]
Is it maybe a case problem in "CoresService.Helpers.cs"?  The GrossCheck function (starting on line 160) seems to be looking for "licenses" instead of "Licenses".

**Comment by samson7point1** [comment]
Yeah, that's the problem. If I just copy "Licenses" to "licenses" and re-run the updater it works fine.  I'll submit a PR.

**Comment by hallem** [comment]
That's on me. I'm pretty sure I just recently changed that so it lined up with the rest of the directories on the card since they start with a capital. I'm not sure we should revert the change though. We can make it support both cases, but prefer the capital to start instead.

**Comment by mattpannella** [comment]
should be good now in the latest release
