### ISSUE TITLE
ServiceUnavailable Error

### ISSUE THREAD

**Issue by TheSKARD1** [mattpannella/pupdate#352]
**Describe the bug**
While running Update All the same error frequently appears.

Uh oh something went wrong.
ServiceUnavailable: https://archive.org/metadata/openFPGA-Files

**To Reproduce**
1. Run pupdate.exe
2. Update All
3. Watch the text scroll by

**Expected behavior**
Something doesn't go wrong.

**Comment by mattpannella** [comment]
archive.org is down after being hacked
disable the asset downloader or switch to the custom archive
