### ISSUE TITLE
Jtbeta.zip contents not extracted in correct locations

### ISSUE THREAD

**Issue by cmcginty** [mattpannella/pupdate#355]
**Describe the bug**
JTbeta cores report there is no beta file installed after running install process.

**To Reproduce**
1. copy jtbeta.zip to root of SD card
2. run pupdate ... and update all
3. system output reports beta files was not installed. Beta cores are not enabled in OpenFPGA.

**Expected behavior**
1. Correctly apply jtbeta.zip contents to all jt cores

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version 12.7.5

**Contents of settings file**

**Comment by cmcginty** [comment]
After checking the destination dir `Assets/jtpatreon/common/` I  found that the jtbeta.bin file was out of date and traced it back to a bad download operation.

**Comment by mattpannella** [comment]
so everything is good now?

**Comment by tbalcom** [comment]
I'm seeing this lately with the jotego.jtngpc core:
> Missing or incorrect License file for the following cores:
jotego.jtngpc

Is this the same issue? It persists after running update-all. I have verified (checked the hashes) the latest beta.bin is in `/Assets/jtpatreon/common/`. The jtbeta.zip is also in the SD card root. Another user on Patreon reported the same problem but for multiple cores (jtmidres, jtngpc, jtriders, jts18, jtwwfss, and jtxmen).

**Comment by mattpannella** [comment]
i think the issue with NGPC is it looks like jotego (accidentally?) removed the bios rom file from the core distro
https://github.com/jotego/jtbin/tree/master/pocket/raw/Assets/jtngpc/jotego.jtngpc
there's nothing in this folder anymore (only the one in _alts). so the bios file from the previous release is still in your local folder, that has the old beta key md5 hash in it, and pupdate compares that file and it's a mismatch

**Comment by mattpannella** [comment]
closing this down for now, as its not an issue with pupdate
