### ISSUE TITLE
Cannot download assets for Vectrex Extras

### ISSUE THREAD

**Issue by Razorbacktrack** [mattpannella/pupdate#356]
**Describe the bug**
Every asset throws the "Not found" message.

**To Reproduce**
1. Pocket Extras
2. Variant Cores
3. Download Vectrex Extras

**Expected behavior**
All assets should be downloaded.

**Desktop (please complete the following information):**
 - OS: Windows 11
 
[pupdate_settings.json](https://github.com/user-attachments/files/17530659/pupdate_settings.json)

**Comment by mattpannella** [comment]
archive.org is still down

**Comment by Razorbacktrack** [comment]
I think that the rom pack is up (vectrex_202408), but I still get "Not found".

**Comment by mattpannella** [comment]
sorry brain fart when i read this originally
no vectrex roms are in the asset archive. only arcade roms are. you gotta byo for vectrex
