### ISSUE TITLE
Missing or incorrect License file for the following cores: jotego.jtngpc

### ISSUE THREAD

**Issue by nickxcom** [mattpannella/pupdate#360]
I get a warning that I am missing or have incorrect license file for the jotego.jtngpc core, despite having jtbeta.zip in root of USB and also manually moving bin file to assets folder

**To Reproduce**
Run update all with JT cores

**Expected behavior**
No warning should be kicked back for JT Cores as the most recent key file exists

I am not 100% sure if this even IS an actual error as I am unsure on the status of this core. I wasn't having any luck with my limited resources/knowledge. I suppose it's possible the NGP and NGPC are somehow related but not sure how that works with licenses

[pupdate_settings.json](https://github.com/user-attachments/files/17792833/pupdate_settings.json)

**Comment by tbalcom** [comment]
There is some information [here](https://github.com/mattpannella/pupdate/issues/355#issuecomment-2461181721).

> i think the issue with NGPC is it looks like jotego (accidentally?) removed the bios rom file from the core distro
https://github.com/jotego/jtbin/tree/master/pocket/raw/Assets/jtngpc/jotego.jtngpc
there's nothing in this folder anymore (only the one in _alts). so the bios file from the previous release is still in your local folder, that has the old beta key md5 hash in it, and pupdate compares that file and it's a mismatch

**Comment by nickxcom** [comment]
> There is some information [here](https://github.com/mattpannella/pupdate/issues/355#issuecomment-2461181721).
> 
> > i think the issue with NGPC is it looks like jotego (accidentally?) removed the bios rom file from the core distro
> > https://github.com/jotego/jtbin/tree/master/pocket/raw/Assets/jtngpc/jotego.jtngpc
> > there's nothing in this folder anymore (only the one in _alts). so the bios file from the previous release is still in your local folder, that has the old beta key md5 hash in it, and pupdate compares that file and it's a mismatch

Ahh thank you so much! I thought I checked issues more thoroughly than I did but missed the closed one. I'll ignore the error for now, thank you for your help!
