### ISSUE TITLE
Dotnet 7.0 is end-of-life

### ISSUE THREAD

**Issue by p-rintz** [mattpannella/pupdate#363]
**Describe the bug**
Dotnet7.0 has reached end of life:

https://dotnet.microsoft.com/en-us/download/dotnet/7.0

> This release has reached end of life, meaning it is no longer supported. We recommend moving to a supported release, such as [.NET 9.0](https://dotnet.microsoft.com/en-us/download/dotnet/9.0). See our [support policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) for more details.

**To Reproduce**

**Expected behavior**
Update dotnet to 8.0 or 9.0

**Screenshots**

**Desktop (please complete the following information):**

**Contents of settings file**
please attach the contents of pupdate_settings.json

**Comment by mattpannella** [comment]
testing .net 9.x at the moment

**Comment by mattpannella** [comment]
https://github.com/mattpannella/pupdate/releases/tag/4.0.0-beta

**Comment by mattpannella** [comment]
4.x is public release now, on .net 9
